name: release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 11

      - uses: robinraju/release-downloader@v1.3
        with:
          repository: "raycoarana/poi-to-discover-media"
          latest: true
          fileName: "*"

      - name: Prepare for execution
        run: |
          mv poi-to-discover-media-*.zip poi-to-discover-media.zip \
          && unzip poi-to-discover-media.zip \
          && mv poi-to-discover-media-* poi-to-discover-media

      - name: Set current date & version
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV \
          && echo "version=$(date +'v%Y%m%d')" >> $GITHUB_ENV

      - name: Download files
        run: kotlin downloader.main.kts ${{ env.date }}

      - name: Generate
        run: generate.sh ${{ env.date }}

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        id: create_github_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: false
          tag_name: "${{ env.date_without_dashes }}"
          name: "speedradar-${{ env.date }}"
          body_path: ${{ github.workspace }}/tmp/release-notes.txt
          files: |
            release-${{ env.date }}//Release-${{ env.date }}-ES.zip
            release-${{ env.date }}//Release-${{ env.date }}-ES-WithoutHiddenAndPhoto.zip
            release-${{ env.date }}//Release-${{ env.date }}-EU.zip
            release-${{ env.date }}//Release-${{ env.date }}-EU-WithoutHiddenAndPhoto.zip
