name: release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 11

      - uses: robinraju/release-downloader@v1.3
        with:
          repository: "raycoarana/poi-to-discover-media"
          latest: true
          fileName: "*"

      - name: Prepare for execution
        run: |
          mv poi-to-discover-media-*.zip poi-to-discover-media.zip \
          && unzip poi-to-discover-media.zip \
          && mv poi-to-discover-media-* poi-to-discover-media

      - name: Set current date
        id: current-date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')" \
          echo "::set-output name=date-without-dashes::$(date +'%Y%m%d')" \

      - name: Download files
        run: kotlin downloader.main.kts ${{ steps.current-date.outputs.date }}

      - name: Generate
        run: generate.sh ${{ steps.current-date.outputs.date }}

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        id: create_github_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: false
          tag_name: "v${{ steps.current-date.outputs.date-without-dashes }}"
          name: "speedradar-${{ steps.current-date.outputs.date }}"
          body_path: ${{ github.workspace }}/tmp/release-notes.txt
          files: |
            release-${{ steps.current-date.outputs.date }}//Release-${{ steps.current-date.outputs.date }}-ES.zip
            release-${{ steps.current-date.outputs.date }}//Release-${{ steps.current-date.outputs.date }}-ES-WithoutHiddenAndPhoto.zip
            release-${{ steps.current-date.outputs.date }}//Release-${{ steps.current-date.outputs.date }}-EU.zip
            release-${{ steps.current-date.outputs.date }}//Release-${{ steps.current-date.outputs.date }}-EU-WithoutHiddenAndPhoto.zip
