name: release
on:
  schedule:
    - cron: "0 8 * * FRI"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5.1

      - uses: robinraju/release-downloader@v1.3
        with:
          repository: "raycoarana/poi-to-discover-media"
          latest: true
          fileName: "*"

      - name: Prepare for execution
        run: |
          mv poi-to-discover-media-*.zip poi-to-discover-media.zip \
          && unzip poi-to-discover-media.zip \
          && mv poi-to-discover-media-* poi-to-discover-media

      - name: Set current date & version
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV \
          && echo "version=$(date +'v%Y%m%d')" >> $GITHUB_ENV

      - name: Download files
        run: gradle run --args="\"{{ secrets.LUFOP_USERNAME}}\" \"{{ secrets.LUFOP_PASSWORD}}\""

      - name: Generate
        run: ./generate.sh ${{ env.date }}

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        id: create_github_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: false
          tag_name: "${{ env.version }}"
          name: "speedradar-${{ env.date }}"
          body_path: ${{ github.workspace }}/tmp/release-notes.txt
          files: |
            release-${{ env.date }}//Release-${{ env.date }}-ES.zip
            release-${{ env.date }}//Release-${{ env.date }}-ES-WithoutHiddenAndPhoto.zip
            release-${{ env.date }}//Release-${{ env.date }}-EU.zip
            release-${{ env.date }}//Release-${{ env.date }}-EU-WithoutHiddenAndPhoto.zip

      - name: Commit & Push new hashes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Update hashes of release ${{ env.date }}"
          branch: master
